name: dsc_project
description: A new Flutter application.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.0
  http: ^0.12.2
  flutter_dotenv: ^2.1.0
  cached_network_image: ^2.5.0
  firebase_auth: ^0.18.4+1
  firebase_core: ^0.5.3
  google_sign_in: ^4.5.1
  flutter_signin_button: ^1.0.0
  modal_progress_hud: ^0.1.3
  photofilters: ^2.0.1
  gallery_saver: ^2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  fonts:
    - family: Montserrat
      fonts:
        - asset: fonts/Montserrat-Regular.ttf

  assets:
    - assets/
    - .env