name: dsc_project
description: A new Flutter application.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.3
  http: ^0.13.3
  flutter_dotenv: ^5.0.0
  cached_network_image: ^3.0.0
  firebase_auth: ^1.4.1
  firebase_core: ^1.3.0
  google_sign_in: ^5.0.4
  flutter_signin_button: ^2.0.0
  modal_progress_hud_nsn: ^0.1.0-nullsafety-1
  photofilters: ^3.0.1
  gallery_saver: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  fonts:
    - family: Montserrat
      fonts:
        - asset: fonts/Montserrat-Regular.ttf

  assets:
    - assets/
    - .env